version : "3.9"

services : 
  server :
    build : ./server
    container_name : express-server
    ports : 
    - "5000:5000"   # host port : docker port
    networks :
    - fullstack
    restart : unless-stopped

  client :
    build : ./client
    container_name : react-client
    ports : 
    - "5173:3000"
    depends_on :
    - server
    networks :
    - fullstack
    restart : unless-stopped

networks :
  fullstack:
    driver : bridge
